workflows:
  ios-workflow:
    name: iOS Workflow - Clean Start
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        APP_ID: app.randomaita.final
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: app.randomaita.final
        TEAM_ID: US86BZ3GH5
      groups:
        - ios_signing  # iOS certificate and profile secrets (CERT_P12_BASE64, P12_PASSWORD, MOBILEPROVISION_BASE64, PROFILE_NAME)
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm ci
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Clear DerivedData
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
      
      - name: Install Certificate and Provisioning Profile
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          
          : "${CERT_P12_BASE64:?missing CERT_P12_BASE64}"
          : "${MOBILEPROVISION_BASE64:?missing MOBILEPROVISION_BASE64}"
          # Optional: PROFILE_NAME; Required now: P12_PASSWORD (non-empty)
          
          KEYCHAIN=build.keychain
          
          b64_decode() { if base64 --help >/dev/null 2>&1; then base64 --decode; else base64 -D; fi; }
          strip_wrap_quotes() { sed 's/^"//; s/"$//'; }
          trim_pw() { tr -d '\r' | sed 's/^[[:space:]]\+//; s/[[:space:]]\+$//'; }
          
          # Normalize password
          P12_PASSWORD_RAW="${P12_PASSWORD-}"
          P12_PASSWORD_CLEAN="$(printf %s "$P12_PASSWORD_RAW" | strip_wrap_quotes | trim_pw)"
          if [ -z "$P12_PASSWORD_CLEAN" ]; then
            echo "ERROR: P12_PASSWORD is required for this certificate."
            exit 1
          fi
          
          # Keychain
          security create-keychain -p "" "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security unlock-keychain -p "" "$KEYCHAIN"
          security set-keychain-settings -lut 7200 "$KEYCHAIN"
          
          # Decode inputs
          printf %s "$CERT_P12_BASE64"        | strip_wrap_quotes | b64_decode > /tmp/cert.p12
          printf %s "$MOBILEPROVISION_BASE64" | strip_wrap_quotes | b64_decode > /tmp/profile.mobileprovision
          
          # Hard hash assertion to prevent stale secrets
          EXPECTED_P12_SHA256="a301c8c8988c2c2cbc2ef72ab2cfb96b4e5deae6ae37725b0176dcb086b158f2"
          ACTUAL_SHA256="$(shasum -a 256 /tmp/cert.p12 2>/dev/null | awk '{print $1}' || echo unknown)"
          
          echo "=== Certificate Debug Info ==="
          echo "P12 file size: $(stat -f%z /tmp/cert.p12 2>/dev/null || stat -c%s /tmp/cert.p12 2>/dev/null || wc -c < /tmp/cert.p12) bytes"
          echo "ASSERT p12 SHA256: $ACTUAL_SHA256"
          echo "P12_PASSWORD length: ${#P12_PASSWORD_CLEAN}"
          
          # Case-insensitive comparison (convert both to lowercase)
          if [ "$(echo "$ACTUAL_SHA256" | tr '[:upper:]' '[:lower:]')" != "$(echo "$EXPECTED_P12_SHA256" | tr '[:upper:]' '[:lower:]')" ]; then
            echo "ERROR: Codemagic is not using the expected certificate. Update CERT_P12_BASE64."
            echo "Expected: $EXPECTED_P12_SHA256"
            echo "Actual:   $ACTUAL_SHA256"
            exit 1
          fi
          
          # Pre-verify with OpenSSL using the SAME password
          if ! openssl pkcs12 -in /tmp/cert.p12 -passin "pass:${P12_PASSWORD_CLEAN}" -nokeys -info >/dev/null 2>&1 \
             && ! openssl pkcs12 -legacy -in /tmp/cert.p12 -passin "pass:${P12_PASSWORD_CLEAN}" -nokeys -info >/dev/null 2>&1; then
            echo "ERROR: OpenSSL cannot open p12 with the provided password (wrong password or corrupt p12)."
            exit 1
          fi
          echo "OpenSSL check: p12 verified WITH password."
          
          # Import (WITH password)
          echo "Import path: WITH password"
          security import /tmp/cert.p12 -k "$KEYCHAIN" -f pkcs12 -P "$P12_PASSWORD_CLEAN" \
            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/xcodebuild
          
          # Allow tools to access the key non-interactively
          security set-key-partition-list -S apple-tool:,apple: -s -k "" "$KEYCHAIN"
          
          # Install provisioning profile
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_PLIST=$(/usr/bin/security cms -D -i /tmp/profile.mobileprovision)
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<<"$PROFILE_PLIST")
          PROFILE_NAME_SAFE=$(/usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin <<<"$PROFILE_PLIST")
          : "${PROFILE_UUID:?Failed to parse profile UUID}"
          cp /tmp/profile.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"
          
          echo "${PROFILE_NAME:-${PROFILE_NAME_SAFE:-}}" > /tmp/profile_name.txt
          echo "$PROFILE_UUID" > /tmp/profile_uuid.txt
          
          echo "✓ Certificate imported and profile installed ($PROFILE_UUID)"
      
      - name: Clean Pods Deterministically
        script: |
          set -euo pipefail
          cd ios/App
          pod repo update
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ../..
      
      - name: Verify Signing Configuration
        script: |
          set -euo pipefail
          cd ios/App
          
          echo "=== App target (Release) ==="
          xcodebuild -showBuildSettings -workspace App.xcworkspace -scheme App -configuration Release 2>/dev/null \
           | grep -E "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER" | sed 's/^[[:space:]]*//'
          
          echo ""
          echo "=== Pods-App target (Release) — expect CODE_SIGNING_ALLOWED = NO ==="
          xcodebuild -showBuildSettings -project Pods/Pods.xcodeproj -target Pods-App -configuration Release 2>/dev/null \
           | grep -E "CODE_SIGNING_ALLOWED|CODE_SIGN_STYLE|PROVISIONING_PROFILE" | sed 's/^[[:space:]]*//' || echo "Pods-App target not found (this is OK if pods not installed yet)"
          
          cd ../..
      
      - name: Build Archive
        script: |
          set -euo pipefail
          cd ios/App
          
          : "${TEAM_ID:?TEAM_ID is not set}"
          : "${BUNDLE_ID:?BUNDLE_ID is not set}"
          
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          
          echo "=== Building Archive ==="
          echo "Bundle ID: $BUNDLE_ID"
          echo "Team ID: $TEAM_ID"
          echo "Archive Path: $ARCHIVE_PATH"
          
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath "$ARCHIVE_PATH" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            2>&1 | tee /tmp/archive_build.log || {
            echo ""
            echo "=== ARCHIVE BUILD FAILED ==="
            echo ""
            echo "Error details from build log:"
            tail -50 /tmp/archive_build.log
            echo ""
            exit 1
          }
          
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "ERROR: Archive was not created at $ARCHIVE_PATH"
            exit 1
          fi
          
          echo "✓ Archive created successfully at $ARCHIVE_PATH"
          cd ../..
      
      - name: Export IPA
        script: |
          set -euo pipefail
          cd ios/App
          
          : "${TEAM_ID:?TEAM_ID is not set}"
          : "${BUNDLE_ID:?BUNDLE_ID is not set}"
          
          PROFILE_NAME=$(cat /tmp/profile_name.txt 2>/dev/null || echo "")
          : "${PROFILE_NAME:?PROFILE_NAME is not set (ensure profile install step wrote it)}"
          
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          [ -d "$ARCHIVE_PATH" ] || { echo "ERROR: Archive not found at $ARCHIVE_PATH"; exit 1; }
          
          # Verify ExportOptions.plist template exists
          if [ ! -f "ExportOptions.plist" ]; then
            echo "ERROR: ExportOptions.plist template not found"
            echo "This file should be committed to git at ios/App/ExportOptions.plist"
            exit 1
          fi
          
          echo "=== Exporting IPA ==="
          SAFE_PROFILE_NAME=${PROFILE_NAME//\"/\\\"}
          
          # Process template safely with PlistBuddy
          cp ExportOptions.plist ExportOptions.processed.plist
          /usr/libexec/PlistBuddy -c "Set :teamID $TEAM_ID" ExportOptions.processed.plist || {
            echo "ERROR: Failed to set teamID in ExportOptions.plist"
            exit 1
          }
          /usr/libexec/PlistBuddy -c "Delete :provisioningProfiles:$BUNDLE_ID" ExportOptions.processed.plist 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Delete :provisioningProfiles:app.randomaita.final" ExportOptions.processed.plist 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:$BUNDLE_ID string $SAFE_PROFILE_NAME" ExportOptions.processed.plist || {
            echo "ERROR: Failed to set provisioning profile in ExportOptions.plist"
            echo "Bundle ID: $BUNDLE_ID"
            echo "Profile Name: $SAFE_PROFILE_NAME"
            exit 1
          }
          
          EXPORT_PATH="$CM_BUILD_DIR/ipa"
          mkdir -p "$EXPORT_PATH"
          
          echo "Export options file: ExportOptions.processed.plist"
          echo "Export options content:"
          cat ExportOptions.processed.plist
          echo ""
          
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$EXPORT_PATH" \
            -exportOptionsPlist ExportOptions.processed.plist \
            2>&1 | tee /tmp/export.log || {
            echo ""
            echo "=== IPA EXPORT FAILED ==="
            echo ""
            echo "Error details from export log:"
            tail -50 /tmp/export.log
            echo ""
            exit 1
          }
          
          IPA_FILE=$(find "$EXPORT_PATH" -name "*.ipa" -type f | head -1 || true)
          [ -n "$IPA_FILE" ] || { 
            echo "ERROR: IPA file not found after export"
            tail -50 /tmp/export.log || true
            exit 1
          }
          
          echo "✓ IPA exported successfully: $IPA_FILE"
          ls -lh "$IPA_FILE"
          
          cd ../..
      
      - name: Upload to TestFlight (Optional)
        script: |
          set -euo pipefail
          
          IPA_FILE=$(find "$CM_BUILD_DIR/ipa" -name "*.ipa" -type f | head -1 || true)
          
          if [ -z "$IPA_FILE" ]; then
            echo "ERROR: IPA file not found in $CM_BUILD_DIR/ipa"
            echo "IPA export must have failed in previous step"
            exit 1
          fi
          
          echo "=== TestFlight Upload (Optional) ==="
          
          # Check if App Store Connect API credentials are available
          if [ -z "${ASC_KEY_ID:-}" ] || [ -z "${ASC_ISSUER_ID:-}" ]; then
            echo "⚠ App Store Connect API credentials not found"
            echo "  ASC_KEY_ID: ${ASC_KEY_ID:-not set}"
            echo "  ASC_ISSUER_ID: ${ASC_ISSUER_ID:-not set}"
            echo ""
            echo "Skipping TestFlight upload."
            echo "The IPA file is available as a Codemagic artifact for manual upload."
            echo ""
            echo "To enable automatic TestFlight upload:"
            echo "1. Create an App Store Connect API key in Apple Developer Portal"
            echo "2. Add ASC_KEY_ID and ASC_ISSUER_ID to Codemagic environment variables"
            echo "3. Or set up the apple_credentials group in Codemagic"
            echo ""
            echo "IPA file location: $IPA_FILE"
            exit 0
          fi
          
          echo "Uploading IPA to TestFlight..."
          echo "IPA: $IPA_FILE"
          echo "Key ID: $ASC_KEY_ID"
          echo "Issuer ID: $ASC_ISSUER_ID"
          
          xcrun altool --upload-app \
            --type ios \
            --file "$IPA_FILE" \
            --apiKey "$ASC_KEY_ID" \
            --apiIssuer "$ASC_ISSUER_ID" \
            2>&1 | tee /tmp/upload.log || {
            echo ""
            echo "⚠ TestFlight upload failed"
            echo ""
            echo "Error details:"
            tail -20 /tmp/upload.log
            echo ""
            echo "The IPA file is still available as a Codemagic artifact."
            echo "You can upload it manually to App Store Connect:"
            echo "1. Download the IPA from Codemagic artifacts"
            echo "2. Go to https://appstoreconnect.apple.com"
            echo "3. Navigate to your app → TestFlight"
            echo "4. Upload the IPA manually"
            echo ""
            exit 0
          }
          
          echo "✓ IPA uploaded to TestFlight successfully"
          echo "Check App Store Connect for processing status"
    
    artifacts:
      - build/ipa/*.ipa
      - build/**/*.xcarchive
      - ios/App/ExportOptions.processed.plist
    
    publishing:
      email:
        recipients:
          - robbyaw@icloud.com
        notify:
          success: true
          failure: true
