workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    # Enable automatic code signing - requires App Store Connect integration in Codemagic UI
    # This will authenticate Xcode with Apple and create provisioning profiles automatically
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.randomaita.final
      vars:
        APP_ID: app.randomaita.final
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: app.randomaita.final
        TEAM_ID: US86BZ3GH5
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          echo "Installing CocoaPods dependencies..."
          pod install --repo-update || {
            echo "Pod install failed, trying without repo update..."
            pod install
          }
          echo "Verifying Pods installation..."
          if [ ! -f "Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig" ]; then
            echo "Warning: Pods config not found, but continuing..."
          else
            echo "✓ Pods installed successfully"
          fi
          echo "Verifying workspace exists..."
          if [ ! -f "App.xcworkspace/contents.xcworkspacedata" ]; then
            echo "ERROR: Workspace file not found!"
            exit 1
          fi
          cd ../..
      - name: Verify scheme exists
        script: |
          cd ios/App
          if [ ! -f "App.xcodeproj/xcshareddata/xcschemes/App.xcscheme" ]; then
            echo "ERROR: Scheme file not found"
            exit 1
          fi
          cd ../..
      - name: Sync Capacitor files
        script: |
          echo "Syncing Capacitor files to iOS directory..."
          npx cap sync ios || {
            echo "Capacitor sync failed!"
            exit 1
          }
          echo "✓ Capacitor sync complete"
          echo "Verifying AppDelegate.swift exists..."
          if [ ! -f "ios/App/App/AppDelegate.swift" ]; then
            echo "ERROR: AppDelegate.swift not found!"
            exit 1
          fi
          echo "✓ AppDelegate.swift found"
          echo "Re-running pod install after Capacitor sync..."
          cd ios/App
          pod install
          cd ../..
      - name: Diagnose App Store Connect signing
        script: |
          echo "=== Diagnosing App Store Connect Signing ==="
          echo "Bundle ID: $BUNDLE_ID"
          echo "Team ID: $TEAM_ID"
          
          # Check if app-store-connect CLI is available
          which app-store-connect || echo "⚠ app-store-connect command not found"
          
          # Test API connection and show current user/team
          echo "Checking API connection..."
          app-store-connect whoami || echo "⚠ Could not authenticate with App Store Connect API"
          
          # List existing App Store profiles for this bundle ID
          echo ""
          echo "Listing existing App Store profiles for $BUNDLE_ID..."
          app-store-connect list-profiles --type IOS_APP_STORE --filter bundleId="$BUNDLE_ID" || {
            echo "⚠ No profiles found or error listing profiles"
            echo "This might be expected if profiles don't exist yet"
          }
          
          echo ""
          echo "If no profiles are listed above, Codemagic will create them automatically during build"
      - name: Set up code signing
        script: |
          echo "=== Code Signing Setup ==="
          echo "Bundle ID: $BUNDLE_ID"
          echo "Team ID: $TEAM_ID"
          
          # Verify environment variables are set
          if [ -z "$BUNDLE_ID" ]; then
            echo "ERROR: BUNDLE_ID not set"
            exit 1
          fi
          if [ -z "$TEAM_ID" ]; then
            echo "ERROR: TEAM_ID not set"
            exit 1
          fi
          
          cd ios/App
          
          # Ensure DEVELOPMENT_TEAM is set in project file
          echo ""
          echo "Setting DEVELOPMENT_TEAM in project file..."
          sed -i.bak "s/DEVELOPMENT_TEAM = \"[^\"]*\";/DEVELOPMENT_TEAM = \"$TEAM_ID\";/g" App.xcodeproj/project.pbxproj || true
          sed -i.bak "s/DEVELOPMENT_TEAM = [^;]*;/DEVELOPMENT_TEAM = \"$TEAM_ID\";/g" App.xcodeproj/project.pbxproj || true
          
          # Ensure CODE_SIGN_STYLE is Automatic
          sed -i.bak "s/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g" App.xcodeproj/project.pbxproj || true
          
          # Verify settings
          if grep -q "DEVELOPMENT_TEAM = \"$TEAM_ID\"" App.xcodeproj/project.pbxproj; then
            echo "✓ DEVELOPMENT_TEAM set correctly"
          else
            echo "⚠ DEVELOPMENT_TEAM may not be set in all configurations"
          fi
          
          if grep -q "CODE_SIGN_STYLE = Automatic" App.xcodeproj/project.pbxproj; then
            echo "✓ CODE_SIGN_STYLE set to Automatic"
          else
            echo "⚠ CODE_SIGN_STYLE may not be set to Automatic"
          fi
          
          cd ../..
          
          # Initialize keychain - REQUIRED for Codemagic code signing
          echo ""
          echo "Initializing keychain for code signing..."
          keychain initialize
          
          # CRITICAL: Explicitly create/fetch the provisioning profile BEFORE building
          # This ensures the profile exists before Xcode tries to use it
          echo ""
          echo "=== Creating App Store Provisioning Profile ==="
          echo "This step ensures the profile exists before the build starts"
          echo "Bundle ID: $BUNDLE_ID"
          
          # Use Codemagic's app-store-connect CLI to create the profile
          # The --create flag creates the profile if it doesn't exist
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --verbose 2>&1 | tee /tmp/signing-setup.log || {
            echo ""
            echo "⚠ Profile creation/fetch failed - checking logs..."
            cat /tmp/signing-setup.log || true
            echo ""
            echo "This might be OK if profile already exists, continuing..."
          }
          
          # Verify profile was created/fetched
          echo ""
          echo "Verifying profile exists..."
          app-store-connect list-profiles --type IOS_APP_STORE --filter bundleId="$BUNDLE_ID" 2>&1 || {
            echo "⚠ Could not verify profile - will attempt to create during build"
          }
          
          # Apply profiles to Xcode project
          echo ""
          echo "Applying profiles to Xcode project..."
          cd ios/App
          xcode-project use-profiles || {
            echo "⚠ Could not apply profiles yet - Xcode will create during build if needed"
          }
          cd ../..
          
          echo ""
          echo "✓ Code signing setup complete"
          echo "Profile should now exist for bundle ID: $BUNDLE_ID"
      - name: Clean build folder
        script: |
          cd ios/App
          echo "Cleaning build folder..."
          xcodebuild clean \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release
          cd ../..
      - name: Build ipa for distribution
        script: |
          cd ios/App
          mkdir -p "$CM_BUILD_DIR"
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          
          echo "Building archive..."
          echo "Workspace: App.xcworkspace"
          echo "Scheme: App"
          echo "Archive path: $ARCHIVE_PATH"
          echo "Team ID: $TEAM_ID"
          echo "Bundle ID: $BUNDLE_ID"
          
          # Verify Pods are properly installed before building
          echo "Verifying Pods installation..."
          if [ ! -d "Pods/Google-Mobile-Ads-SDK" ]; then
            echo "ERROR: Google-Mobile-Ads-SDK not found in Pods!"
            echo "Running pod install again..."
            pod install
          fi
          
          # Verify workspace file exists
          if [ ! -f "App.xcworkspace/contents.xcworkspacedata" ]; then
            echo "ERROR: Workspace file not found!"
            exit 1
          fi
          
          # Build with automatic provisioning
          # The -allowProvisioningUpdates flag allows Xcode to create profiles automatically
          # Codemagic's ios_signing should also help create profiles
          echo ""
          echo "Starting archive build..."
          echo "This will automatically create provisioning profiles if they don't exist"
          echo "Using Team ID: $TEAM_ID, Bundle ID: $BUNDLE_ID"
          
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath "$ARCHIVE_PATH" \
            -allowProvisioningUpdates \
            -destination "generic/platform=iOS" \
            -configuration Release \
            -UseModernBuildSystem=1 \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            PROVISIONING_PROFILE_SPECIFIER="" \
            SWIFT_VERSION=5.0 \
            SWIFT_OPTIMIZATION_LEVEL="-O" \
            CLANG_ENABLE_MODULES=YES \
            SWIFT_ENABLE_BATCH_MODE=YES \
            2>&1 | tee /tmp/xcodebuild.log || {
            echo ""
            echo "=== BUILD FAILED ==="
            echo "Last 200 lines of build log:"
            tail -200 /tmp/xcodebuild.log
            echo ""
            echo "=== SEARCHING FOR KEY ERRORS ==="
            echo "Provisioning profile errors:"
            grep -i "profile\|provisioning" /tmp/xcodebuild.log | tail -20
            echo ""
            echo "Code signing errors:"
            grep -i "sign\|certificate" /tmp/xcodebuild.log | tail -20
            echo ""
            echo "Bundle ID errors:"
            grep -i "bundle\|identifier" /tmp/xcodebuild.log | tail -20
            echo ""
            echo "General errors:"
            grep -i "error\|failed\|cannot" /tmp/xcodebuild.log | tail -30
            exit 1
          }
          
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "ERROR: Archive not created at $ARCHIVE_PATH"
            echo "Build log:"
            tail -100 /tmp/xcodebuild.log
            exit 1
          fi
          echo "✓ Archive created successfully at $ARCHIVE_PATH"
          cd ../..
      - name: Export IPA
        script: |
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "ERROR: Archive not found at $ARCHIVE_PATH"
            exit 1
          fi
          
          # Verify export_options.plist exists and has team ID
          if [ ! -f "export_options.plist" ]; then
            echo "ERROR: export_options.plist not found"
            exit 1
          fi
          
          echo "Exporting IPA with team ID: $TEAM_ID"
          echo "Note: Codemagic should automatically create distribution certificates via App Store Connect API"
          
          # Export - Codemagic's App Store Connect API integration should provide certificates
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$CM_BUILD_DIR" \
            -allowProvisioningUpdates
          
          # Verify IPA was created
          IPA_FILE=$(find "$CM_BUILD_DIR" -name "*.ipa" -type f | head -1)
          if [ -n "$IPA_FILE" ]; then
            echo "✓ IPA exported successfully: $IPA_FILE"
            ls -la "$IPA_FILE"
          else
            echo "ERROR: IPA not found after export"
            echo ""
            echo "This error means Codemagic couldn't create distribution certificates."
            echo "Make sure:"
            echo "1. App Store Connect API integration 'apple_credentials' is configured in Codemagic"
            echo "2. The API key has 'App Manager' or 'Admin' role"
            echo "3. The bundle ID 'app.randomaita.final' is registered in App Store Connect"
            echo ""
            echo "Contents of export directory:"
            ls -la "$CM_BUILD_DIR"
            exit 1
          fi
    artifacts:
      - build/**/*.xcarchive
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - robbyaw@icloud.com
        notify:
          success: true
          failure: true
