workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials
      vars:
        APP_ID: com.randomaita.app
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: com.randomaita.app
        TEAM_ID: US86BZ3GH5
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update
          echo "Verifying CocoaPods installation..."
          ls -la Pods/Target\ Support\ Files/Pods-App/ || echo "Warning: Pods directory not found"
          ls -la App.xcworkspace || echo "Warning: Workspace not found"
          cd ../..
      - name: Create shared scheme (required for workspace builds)
        script: |
          cd ios/App
          # Create scheme directory if it doesn't exist
          mkdir -p App.xcodeproj/xcshareddata/xcschemes
          # Force create the scheme file (overwrite if exists)
          echo "Creating shared scheme: App.xcscheme"
          printf '<?xml version="1.0" encoding="UTF-8"?>\n<Scheme\n   LastUpgradeVersion = "1500"\n   version = "1.7">\n   <BuildAction>\n      <BuildActionEntries>\n         <BuildActionEntry\n            buildForTesting = "YES"\n            buildForRunning = "YES"\n            buildForProfiling = "YES"\n            buildForArchiving = "YES"\n            buildForAnalyzing = "YES">\n            <BuildableReference\n               BuildableIdentifier = "primary"\n               BlueprintIdentifier = "504EC3031FED79650016851F"\n               BuildableName = "App.app"\n               BlueprintName = "App"\n               ReferencedContainer = "container:App.xcodeproj">\n            </BuildableReference>\n         </BuildActionEntry>\n      </BuildActionEntries>\n   </BuildAction>\n   <TestAction>\n      <Testables>\n      </Testables>\n   </TestAction>\n   <LaunchAction\n      buildConfiguration = "Debug"\n      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"\n      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"\n      launchStyle = "0">\n      <BuildableProductRunnable\n         runnableDebuggingMode = "0">\n         <BuildableReference\n            BuildableIdentifier = "primary"\n            BlueprintIdentifier = "504EC3031FED79650016851F"\n            BuildableName = "App.app"\n            BlueprintName = "App"\n            ReferencedContainer = "container:App.xcodeproj">\n         </BuildableReference>\n      </BuildableProductRunnable>\n   </LaunchAction>\n   <ArchiveAction\n      buildConfiguration = "Release"\n      revealArchiveInOrganizer = "YES">\n   </ArchiveAction>\n</Scheme>\n' > App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
          ls -la App.xcodeproj/xcshareddata/xcschemes/
          cd ../..
      - name: Set up code signing settings on Xcode project
        script: |
          cd ios/App
          xcode-project use-profiles \
            --team-id $TEAM_ID \
            --bundle-id $BUNDLE_ID \
            --workspace App.xcworkspace
          cd ../..
      - name: Verify workspace and scheme
        script: |
          echo "Listing schemes in workspace..."
          xcodebuild -workspace "$XCODE_WORKSPACE" -list || echo "Workspace listing failed"
      - name: Build ipa for distribution
        script: |
          # ALWAYS use workspace (required for CocoaPods - project build will fail)
          echo "Building with workspace: $XCODE_WORKSPACE"
          echo "Using scheme: $XCODE_SCHEME"
          xcodebuild build archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$CM_BUILD_DIR/build.xcarchive" \
            -allowProvisioningUpdates \
            -destination "generic/platform=iOS"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build.xcarchive" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$CM_BUILD_DIR"
    artifacts:
      - build/**/*.xcarchive
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - robbyaw@icloud.com
        notify:
          success: true
          failure: false

