workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials
      vars:
        APP_ID: com.randomaita.app
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: com.randomaita.app
        TEAM_ID: US86BZ3GH5
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update
          echo "Verifying CocoaPods installation..."
          ls -la Pods/Target\ Support\ Files/Pods-App/ || echo "Warning: Pods directory not found"
          ls -la App.xcworkspace || echo "Warning: Workspace not found"
          cd ../..
      - name: Set up code signing settings on Xcode project
        script: |
          cd ios/App
          xcode-project use-profiles \
            --team-id $TEAM_ID \
            --bundle-id $BUNDLE_ID \
            --workspace App.xcworkspace
          cd ../..
      - name: Verify workspace and schemes
        script: |
          echo "Listing schemes in workspace..."
          xcodebuild -workspace "$XCODE_WORKSPACE" -list
      - name: Build ipa for distribution
        script: |
          # Always use workspace (required for CocoaPods)
          xcodebuild build archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$CM_BUILD_DIR/build.xcarchive" \
            -allowProvisioningUpdates \
            -destination "generic/platform=iOS"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build.xcarchive" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$CM_BUILD_DIR"
    artifacts:
      - build/**/*.xcarchive
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - robbyaw@icloud.com
        notify:
          success: true
          failure: false

