workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials
      vars:
        APP_ID: com.randomaita.app
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: com.randomaita.app
        TEAM_ID: US86BZ3GH5
    triggering:
      branch:
        - main
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update
          echo "Verifying CocoaPods installation..."
          ls -la Pods/Target\ Support\ Files/Pods-App/Pods-App.release.xcconfig || echo "Warning: Pods config not found"
          cd ../..
      - name: Verify scheme exists
        script: |
          cd ios/App
          if [ ! -f "App.xcodeproj/xcshareddata/xcschemes/App.xcscheme" ]; then
            echo "ERROR: Scheme file not found"
            exit 1
          fi
          cd ../..
      - name: Set up code signing
        script: |
          cd ios/App
          # Set DEVELOPMENT_TEAM in project file
          awk -v team="$TEAM_ID" '/CODE_SIGN_STYLE = Automatic;/ {print; print "\t\t\tDEVELOPMENT_TEAM = \"" team "\";"; next} {print}' App.xcodeproj/project.pbxproj > App.xcodeproj/project.pbxproj.new && mv App.xcodeproj/project.pbxproj.new App.xcodeproj/project.pbxproj
          sed -i.bak "s/DEVELOPMENT_TEAM = \"[^\"]*\";/DEVELOPMENT_TEAM = \"$TEAM_ID\";/g" App.xcodeproj/project.pbxproj
          
          # Use Codemagic's code signing (should create profiles automatically)
          xcode-project use-profiles \
            --team-id $TEAM_ID \
            --bundle-id $BUNDLE_ID \
            --workspace App.xcworkspace || \
          xcode-project use-profiles \
            --team-id $TEAM_ID \
            --bundle-id $BUNDLE_ID \
            --project App.xcodeproj
          cd ../..
      - name: Build ipa for distribution
        script: |
          cd ios/App
          mkdir -p "$CM_BUILD_DIR"
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath "$ARCHIVE_PATH" \
            -allowProvisioningUpdates \
            -destination "generic/platform=iOS" \
            -configuration Release \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Automatic
          
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "ERROR: Archive not created"
            exit 1
          fi
          cd ../..
      - name: Export IPA
        script: |
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$CM_BUILD_DIR"
    artifacts:
      - build/**/*.xcarchive
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - robbyaw@icloud.com
        notify:
          success: true
          failure: true
