workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - apple_credentials
      vars:
        APP_ID: com.randomaita.app
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: com.randomaita.app
        TEAM_ID: US86BZ3GH5
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          # Ensure we're in project root for path resolution
          echo "Current directory: $(pwd)"
          echo "Verifying node_modules installation..."
          
          # Verify Capacitor is installed
          if [ ! -d "node_modules/@capacitor/ios" ]; then
            echo "Capacitor iOS not found - running npm install..."
            npm install
          fi
          
          # Verify the exact path the Podfile expects
          PODS_HELPER_PATH="../../../../node_modules/@capacitor/ios/scripts/pods_helpers.rb"
          if [ -f "$PODS_HELPER_PATH" ]; then
            echo "✓ Pods helper found at relative path from ios/App"
          else
            echo "✗ Pods helper NOT found at expected relative path"
            echo "Checking from project root..."
            if [ -f "node_modules/@capacitor/ios/scripts/pods_helpers.rb" ]; then
              echo "✓ Pods helper exists at project root"
              echo "The Podfile path might be wrong for this directory structure"
            fi
          fi
          
          # Run pod install from ios/App directory (where Podfile is)
          cd ios/App
          echo "Running pod install from: $(pwd)"
          pod install --repo-update
          
          echo "Verifying CocoaPods installation..."
          ls -la Pods/Target\ Support\ Files/Pods-App/ || echo "Warning: Pods directory not found"
          ls -la App.xcworkspace || echo "Warning: Workspace not found"
          
          # Verify config files exist
          if [ -f "Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig" ]; then
            echo "✓ CocoaPods release config found"
          else
            echo "✗ CocoaPods release config NOT found"
            echo "Current directory: $(pwd)"
            echo "Checking for Pods directory..."
            ls -la Pods/ || echo "Pods directory doesn't exist"
            echo "Pod install may have failed - check output above"
          fi
          if [ -f "Pods/Target Support Files/Pods-App/Pods-App.debug.xcconfig" ]; then
            echo "✓ CocoaPods debug config found"
          else
            echo "✗ CocoaPods debug config NOT found"
          fi
          cd ../..
      - name: Verify scheme exists
        script: |
          cd ios/App
          echo "Checking if scheme file exists..."
          if [ -f "App.xcodeproj/xcshareddata/xcschemes/App.xcscheme" ]; then
            echo "✓ Scheme file found"
            ls -la App.xcodeproj/xcshareddata/xcschemes/
          else
            echo "✗ Scheme file not found - this should be committed to the repository"
            exit 1
          fi
          cd ../..
      - name: Set up code signing settings on Xcode project
        script: |
          cd ios/App
          xcode-project use-profiles \
            --team-id $TEAM_ID \
            --bundle-id $BUNDLE_ID \
            --workspace App.xcworkspace
          cd ../..
      - name: Verify workspace and scheme
        script: |
          echo "Listing schemes in workspace..."
          xcodebuild -workspace "$XCODE_WORKSPACE" -list || echo "Workspace listing failed"
          echo ""
          echo "Listing schemes in project..."
          xcodebuild -project ios/App/App.xcodeproj -list || echo "Project listing failed"
          echo ""
          echo "Checking if scheme file exists..."
          ls -la ios/App/App.xcodeproj/xcshareddata/xcschemes/ || echo "Scheme directory not found"
          echo ""
          echo "Checking workspace contents..."
          ls -la ios/App/App.xcworkspace/contents.xcworkspacedata || echo "Workspace file not found"
      - name: Build ipa for distribution
        script: |
          cd ios/App
          # Ensure archive directory exists
          mkdir -p "$CM_BUILD_DIR"
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          echo "Archive will be created at: $ARCHIVE_PATH"
          
          # Verify Pods files exist before building
          echo "Verifying CocoaPods setup..."
          if [ ! -f "Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig" ]; then
            echo "ERROR: CocoaPods config files not found - re-running pod install..."
            pod install
            if [ ! -f "Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig" ]; then
              echo "ERROR: CocoaPods setup failed - cannot proceed"
              exit 1
            fi
          fi
          
          # List schemes
          echo "Listing schemes in project..."
          xcodebuild -project App.xcodeproj -list
          
          # Try building with workspace by specifying scheme file directly
          # The workspace needs the scheme, but we can try to work around it
          echo "Attempting to build with workspace and explicit scheme..."
          
          # Check if we can use the workspace with the scheme
          SCHEME_FILE="App.xcodeproj/xcshareddata/xcschemes/App.xcscheme"
          if [ -f "$SCHEME_FILE" ]; then
            echo "Scheme file exists, trying workspace build..."
            # Use workspace but xcodebuild should find the scheme from the project
            xcodebuild archive \
              -workspace App.xcworkspace \
              -scheme App \
              -archivePath "$ARCHIVE_PATH" \
              -allowProvisioningUpdates \
              -destination "generic/platform=iOS" \
              -configuration Release 2>&1 | head -100 || \
            (
              echo "Workspace build failed, trying project build with explicit Pods path..."
              # Fallback: build from project but set xcconfig path explicitly
              export XCODE_XCCONFIG_FILE="$(pwd)/Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig"
              xcodebuild archive \
                -project App.xcodeproj \
                -scheme App \
                -archivePath "$ARCHIVE_PATH" \
                -allowProvisioningUpdates \
                -destination "generic/platform=iOS" \
                -configuration Release
            )
          else
            echo "ERROR: Scheme file not found!"
            exit 1
          fi
          
          # Check exit status
          BUILD_EXIT_CODE=$?
          echo "Build exit code: $BUILD_EXIT_CODE"
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo "ERROR: Archive build failed with exit code $BUILD_EXIT_CODE"
            exit $BUILD_EXIT_CODE
          fi
          
          # Verify archive was created
          echo "Checking if archive was created..."
          if [ -d "$ARCHIVE_PATH" ]; then
            echo "SUCCESS: Archive created at $ARCHIVE_PATH"
            ls -la "$ARCHIVE_PATH"
          else
            echo "WARNING: Archive not found at expected path, searching..."
            find . -name "*.xcarchive" -type d
            exit 1
          fi
          cd ../..
      - name: Export IPA
        script: |
          echo "Looking for archive..."
          find . -name "*.xcarchive" -type d 2>/dev/null | head -5
          echo ""
          echo "Checking CM_BUILD_DIR: $CM_BUILD_DIR"
          ls -la "$CM_BUILD_DIR" || echo "CM_BUILD_DIR not found"
          echo ""
          # Try to find the archive
          ARCHIVE_PATH=$(find . -name "*.xcarchive" -type d 2>/dev/null | head -1)
          if [ -z "$ARCHIVE_PATH" ]; then
            ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          fi
          echo "Using archive path: $ARCHIVE_PATH"
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "ERROR: Archive not found at $ARCHIVE_PATH"
            echo "Searching for archives..."
            find . -name "*.xcarchive" -type d
            exit 1
          fi
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$CM_BUILD_DIR"
    artifacts:
      - build/**/*.xcarchive
      - build/**/*.ipa
    publishing:
      email:
        recipients:
          - robbyaw@icloud.com
        notify:
          success: true
          failure: false

