workflows:
  ios-workflow:
    name: iOS Workflow - Clean Start
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        APP_ID: app.randomaita.final
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: app.randomaita.final
        TEAM_ID: US86BZ3GH5
      groups:
        - ios_signing  # iOS certificate and profile secrets
        - apple_credentials  # Optional: App Store Connect API (for TestFlight upload)
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm ci
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
          cd ../..
      
      - name: Import Distribution Certificate
        script: |
          set -euo pipefail
          
          echo "=== Importing Distribution Certificate ==="
          
          # Decode certificate from secret
          CERT_FILE=$(mktemp)
          echo "$IOS_DISTRIBUTION_CERT" | base64 -d > "$CERT_FILE"
          
          # Verify certificate file
          CERT_SIZE=$(wc -c < "$CERT_FILE" | tr -d ' ')
          echo "Certificate size: $CERT_SIZE bytes"
          
          if [ "$CERT_SIZE" -lt 1000 ]; then
            echo "ERROR: Certificate file too small - check base64 encoding"
            exit 1
          fi
          
          # Initialize keychain
          keychain initialize
          
          # Import certificate
          echo "Importing certificate with password..."
          keychain add-certificates \
            --certificate "$CERT_FILE" \
            --certificate-password "$IOS_CERT_PASSWORD"
          
          # Verify import
          security find-identity -v -p codesigning | grep "Apple Distribution" || {
            echo "WARNING: Apple Distribution certificate not found in keychain"
          }
          
          rm -f "$CERT_FILE"
          echo "✓ Certificate imported successfully"
      
      - name: Install Provisioning Profile
        script: |
          set -euo pipefail
          
          echo "=== Installing Provisioning Profile ==="
          
          # Decode profile from secret
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILE_DIR"
          
          PROFILE_FILE="$PROFILE_DIR/RandomAITAFinal_AppStore_New.mobileprovision"
          echo "$IOS_PROFILE_APP_STORE_BASE64" | base64 -d > "$PROFILE_FILE"
          
          # Verify profile
          PROFILE_SIZE=$(wc -c < "$PROFILE_FILE" | tr -d ' ')
          echo "Profile size: $PROFILE_SIZE bytes"
          
          if [ "$PROFILE_SIZE" -lt 1000 ]; then
            echo "ERROR: Profile file too small - check base64 encoding"
            exit 1
          fi
          
          # Read profile metadata (Name and UUID)
          PROFILE_PLIST=$(security cms -D -i "$PROFILE_FILE")
          PROFILE_NAME=$(echo "$PROFILE_PLIST" | /usr/libexec/PlistBuddy -c "Print :Name" /dev/stdin 2>/dev/null || echo "RandomAITAFinal_AppStore_New")
          PROFILE_UUID=$(echo "$PROFILE_PLIST" | /usr/libexec/PlistBuddy -c "Print :UUID" /dev/stdin 2>/dev/null || echo "")
          
          echo "Profile Name: $PROFILE_NAME"
          echo "Profile UUID: $PROFILE_UUID"
          
          # Save profile name to file for use in later steps
          echo "$PROFILE_NAME" > /tmp/profile_name.txt
          
          echo "✓ Provisioning profile installed"
      
      - name: Configure Xcode Project
        script: |
          set -euo pipefail
          cd ios/App
          
          # Read profile name from file (set in previous step)
          PROFILE_NAME=$(cat /tmp/profile_name.txt 2>/dev/null || echo "RandomAITAFinal_AppStore_New")
          
          echo "Configuring Xcode project for manual code signing..."
          echo "Profile: $PROFILE_NAME"
          echo "Team ID: $TEAM_ID"
          echo "Bundle ID: $BUNDLE_ID"
          
          # Set development team (if not already set)
          sed -i.bak "s/DEVELOPMENT_TEAM = [^;]*;/DEVELOPMENT_TEAM = $TEAM_ID;/g" App.xcodeproj/project.pbxproj || true
          
          # Note: Command-line parameters in xcodebuild will override project settings
          # So we don't need to modify the project file extensively
          
          cd ../..
          echo "✓ Xcode project ready (signing settings will be set via command-line)"
      
      - name: Build Archive
        script: |
          set -euo pipefail
          cd ios/App
          
          # Read profile name from file
          PROFILE_NAME=$(cat /tmp/profile_name.txt 2>/dev/null || echo "RandomAITAFinal_AppStore_New")
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          
          echo "Building archive with profile: $PROFILE_NAME"
          
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -archivePath "$ARCHIVE_PATH" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID"
          
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "ERROR: Archive not created"
            exit 1
          fi
          
          echo "✓ Archive created successfully"
          cd ../..
      
      - name: Export IPA
        script: |
          set -euo pipefail
          
          # Read profile name from file
          PROFILE_NAME=$(cat /tmp/profile_name.txt 2>/dev/null || echo "RandomAITAFinal_AppStore_New")
          ARCHIVE_PATH="$CM_BUILD_DIR/build.xcarchive"
          
          # Create export options
          cat > export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>$TEAM_ID</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE_ID</key>
              <string>$PROFILE_NAME</string>
            </dict>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF
          
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$CM_BUILD_DIR"
          
          IPA_FILE=$(find "$CM_BUILD_DIR" -name "*.ipa" -type f | head -1)
          if [ -z "$IPA_FILE" ]; then
            echo "ERROR: IPA not found"
            exit 1
          fi
          
          echo "✓ IPA exported: $IPA_FILE"
          ls -lh "$IPA_FILE"
      
      - name: Upload to TestFlight (Optional)
        script: |
          set -euo pipefail
          
          IPA_FILE=$(find "$CM_BUILD_DIR" -name "*.ipa" -type f | head -1)
          
          if [ -z "$IPA_FILE" ]; then
            echo "ERROR: IPA file not found"
            exit 1
          fi
          
          # Check if App Store Connect API credentials are available
          if [ -z "${ASC_KEY_ID:-}" ] || [ -z "${ASC_ISSUER_ID:-}" ]; then
            echo "⚠ App Store Connect API credentials not found"
            echo "Skipping TestFlight upload. You can upload manually from Codemagic artifacts."
            echo "IPA file: $IPA_FILE"
            exit 0
          fi
          
          echo "Uploading to TestFlight..."
          xcrun altool --upload-app \
            --type ios \
            --file "$IPA_FILE" \
            --apiKey "$ASC_KEY_ID" \
            --apiIssuer "$ASC_ISSUER_ID" || {
            echo "⚠ TestFlight upload failed, but IPA is available as artifact"
            exit 0
          }
          
          echo "✓ Uploaded to TestFlight"
    
    artifacts:
      - build/**/*.ipa
      - build/**/*.xcarchive
    
    publishing:
      email:
        recipients:
          - robbyaw@icloud.com
        notify:
          success: true
          failure: true
