platform :ios, '14.0'
use_frameworks! :linkage => :static
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

target 'App' do
  capacitor_pods
end

post_install do |installer|
  assertDeploymentTarget(installer, '14.0')
end
