ENV['COCOAPODS_DISABLE_STATS'] = 'true'

platform :ios, '14.0'
use_modular_headers!
use_frameworks! :linkage => :static
install! 'cocoapods', :deterministic_uuids => true

require_relative '../capacitor-cordova-ios-plugins/podHelpers'

def capacitor_pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'App' do
  capacitor_pods

  # Use the plugin directly from node_modules (bypass spec repo completely)
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'

  # DO NOT add Google-Mobile-Ads-SDK or any Firebase pods here.
  # The Admob plugin declares exactly what it needs.

  post_install do |installer|
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |cfg|
        cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        cfg.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        cfg.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        cfg.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        # Force Swift 5.9 across pods (Xcode 16 defaults to Swift 6)
        cfg.build_settings['SWIFT_VERSION'] = '5.9'
        cfg.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      end
    end

    # Also force Swift 5.9 on the App.xcodeproj build settings
    app_project_path = File.join(__dir__, 'App.xcodeproj')
    if File.exist?(app_project_path)
      xcodeproj = Xcodeproj::Project.open(app_project_path)
      xcodeproj.targets.each do |t|
        t.build_configurations.each do |cfg|
          cfg.build_settings['SWIFT_VERSION'] = '5.9'
          cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
          cfg.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
      end
      xcodeproj.save
    end
  end
end
